-- ============================================
-- Parking Lot Management System - DB Schema
-- Compatible with TiDB (MySQL protocol)
-- ============================================

CREATE DATABASE IF NOT EXISTS parking_lot_db;
USE parking_lot_db;

-- Users table (for login) - supports both admin and customer accounts
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255) NOT NULL, -- bcrypt hashed
    role ENUM('admin', 'customer') DEFAULT 'customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Slots table (represents the parking-slot Array/List)
CREATE TABLE IF NOT EXISTS slots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slot_number INT UNIQUE NOT NULL,
    status ENUM('available', 'occupied') DEFAULT 'available'
);

-- Vehicles table (currently parked vehicles - backs the HashMap)
CREATE TABLE IF NOT EXISTS vehicles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehicle_number VARCHAR(20) UNIQUE NOT NULL,
    vehicle_type VARCHAR(30) NOT NULL,
    owner_name VARCHAR(100),
    owner_contact VARCHAR(30),
    slot_number INT,
    entry_time DATETIME NOT NULL,
    status ENUM('parked', 'exited') DEFAULT 'parked'
);

-- Waiting queue table (backs the Queue data structure)
CREATE TABLE IF NOT EXISTS waiting_queue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehicle_number VARCHAR(20) UNIQUE NOT NULL,
    vehicle_type VARCHAR(30) NOT NULL,
    owner_name VARCHAR(100),
    owner_contact VARCHAR(30),
    added_time DATETIME NOT NULL
);

-- Historical parking records (for completed parking sessions)
CREATE TABLE IF NOT EXISTS parking_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehicle_number VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(30) NOT NULL,
    slot_number INT NOT NULL,
    entry_time DATETIME NOT NULL,
    exit_time DATETIME NOT NULL,
    duration_minutes INT NOT NULL,
    fee DECIMAL(10, 2) NOT NULL
);

-- Bookings table (advance reservations: a customer reserves a specific
-- slot for a chosen time window, picked from a theater-seat-style grid)
CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    slot_number INT NOT NULL,
    vehicle_number VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(30) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    status ENUM('booked', 'cancelled', 'completed') DEFAULT 'booked',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Seed a default admin user -> username: admin | password: admin123
-- (password hash is generated by backend/seed.js, not hardcoded here)

-- Seed 10 default parking slots
INSERT IGNORE INTO slots (slot_number, status)
VALUES (1,'available'),(2,'available'),(3,'available'),(4,'available'),(5,'available'),
       (6,'available'),(7,'available'),(8,'available'),(9,'available'),(10,'available');
